### ISSUE TITLE
I'm not able to run any tests both in Intellij and in using command line

### ISSUE THREAD

**Issue by m-debugger** [pysaumont/fpinkotlin#7]
Hi @pysaumont,
I have imported the project as per the README, but I'm not able to run any tests both in Intellij and in using command line.

Im using:
Gradle 5.4.1 
Intellij 2019.1.3

**Comment by pysaumont** [comment]
Hi,

Difficult to help you since you give no information about what you did and what result you got.

How did you import the project? How did you try to launch the tests? What was the result? (Error messages?)

For example, if you cloned the project from IntelliJ, it is possible that IntelliJ failed at creating the project, using the git project directory for the Kotlin project directory. If this is the case, the Kotlin files are not seen as code and there are no icons for launching the tests. The solution to this particular problem is to reimport the project selecting fpinkotlin-parent as the project directory.

**Comment by pysaumont** [comment]
It seems not to work with IntelliJ 2019.1.3. I just installed this version and could not run the tests. I rolled back to 2019.1.2 and it is working again using the Platform Test Runner (Settings/Build, Execution, Deployment/Runner.

Unfortunately, I will not be able to do further testing until next Monday.

**Comment by m-debugger** [comment]
It started working after I downgraded to 2019.1.1 and Gradle 4.10. It would to get it working with Gradle 5+ and Intelij 2019.1.3

**Comment by pysaumont** [comment]
I have pushed a version that works for me, both with Gradle and IntelliJ 2019.1.3. (It was not easy to find the relevant information!)

Beware that listings 13 and 14 in chapter 13 (Actors) is now broken because there were changes in Kotlin coroutines that I have not handled yet.
