### ISSUE TITLE
Why did you remove Gradle wrapper?

### ISSUE THREAD

**Issue by m-debugger** [pysaumont/fpinkotlin#8]
Hi @pysaumont Can you please explain why you removed Gradle wrapper from the repo?

**Comment by pysaumont** [comment]
It's because the Gradle wrapper is tied to a specific version of Gradle. That's why I don't use it. A reader asked me if he could add a Gradle wrapper to the project. I accepted and all went fine until it stopped working. The wrapper should have been upgraded to the current version of Gradle.

In production, you might want to use the wrapper to ensure your build will always work. This implies not doing modification to your build to benefit from new functionalities. I the context of a book, I prefer to update the build to be up to date with the current version of Gradle.

However, this is not always easy. It appears that tests do not work with the last version of Gradle. I would not have known this if not for your message. (I have not been touching the project for long!) Know, I will have a look to see how this can be fixed. If you have ideas, you're welcome to provide o solution.

Note that IntelliJ is now using Gradle by default for the build, code execution, and test execution. So you have to disable this to use the IntelliJ build and runners. Worse, it seems that it does not work this the last version of IntelliJ I updated to, which was an EAP version. I will check this too.

**Comment by pysaumont** [comment]
Eventually, it appears to be working with IntelliJ 2019.1.3 using the IntelliJ test runner. I will now check what the problem is with Gradle.
